package Modelo;
// Generated 06-dic-2022 2:17:53 by Hibernate Tools 4.3.1



/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private int codigoEquipo;
     private String nombreEquipo;
     private String paisEquipo;
     private int puntosEquipo;
     private int partidosGanadosEquipo;

    public Equipos() {
    }

    public Equipos(int codigoEquipo, String nombreEquipo, String paisEquipo, int puntosEquipo, int partidosGanadosEquipo) {
       this.codigoEquipo = codigoEquipo;
       this.nombreEquipo = nombreEquipo;
       this.paisEquipo = paisEquipo;
       this.puntosEquipo = puntosEquipo;
       this.partidosGanadosEquipo = partidosGanadosEquipo;
    }
   
    public int getCodigoEquipo() {
        return this.codigoEquipo;
    }
    
    public void setCodigoEquipo(int codigoEquipo) {
        this.codigoEquipo = codigoEquipo;
    }
    public String getNombreEquipo() {
        return this.nombreEquipo;
    }
    
    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }
    public String getPaisEquipo() {
        return this.paisEquipo;
    }
    
    public void setPaisEquipo(String paisEquipo) {
        this.paisEquipo = paisEquipo;
    }
    public int getPuntosEquipo() {
        return this.puntosEquipo;
    }
    
    public void setPuntosEquipo(int puntosEquipo) {
        this.puntosEquipo = puntosEquipo;
    }
    public int getPartidosGanadosEquipo() {
        return this.partidosGanadosEquipo;
    }
    
    public void setPartidosGanadosEquipo(int partidosGanadosEquipo) {
        this.partidosGanadosEquipo = partidosGanadosEquipo;
    }




}


