package Modelo;
// Generated 06-dic-2022 2:17:53 by Hibernate Tools 4.3.1



/**
 * Jugadores generated by hbm2java
 */
public class Jugadores  implements java.io.Serializable {


     private int cedula;
     private String nombreJugador;
     private String equipoJugador;
     private int numAmarillas;
     private int numRojas;
     private int numGoles;

    public Jugadores() {
    }

    public Jugadores(int cedula, String nombreJugador, String equipoJugador, int numAmarillas, int numRojas, int numGoles) {
       this.cedula = cedula;
       this.nombreJugador = nombreJugador;
       this.equipoJugador = equipoJugador;
       this.numAmarillas = numAmarillas;
       this.numRojas = numRojas;
       this.numGoles = numGoles;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombreJugador() {
        return this.nombreJugador;
    }
    
    public void setNombreJugador(String nombreJugador) {
        this.nombreJugador = nombreJugador;
    }
    public String getEquipoJugador() {
        return this.equipoJugador;
    }
    
    public void setEquipoJugador(String equipoJugador) {
        this.equipoJugador = equipoJugador;
    }
    public int getNumAmarillas() {
        return this.numAmarillas;
    }
    
    public void setNumAmarillas(int numAmarillas) {
        this.numAmarillas = numAmarillas;
    }
    public int getNumRojas() {
        return this.numRojas;
    }
    
    public void setNumRojas(int numRojas) {
        this.numRojas = numRojas;
    }
    public int getNumGoles() {
        return this.numGoles;
    }
    
    public void setNumGoles(int numGoles) {
        this.numGoles = numGoles;
    }




}


