package Modelo;
// Generated 06-dic-2022 2:17:53 by Hibernate Tools 4.3.1



/**
 * Partidos generated by hbm2java
 */
public class Partidos  implements java.io.Serializable {


     private Integer codigoPartido;
     private String manejoEquipo1;
     private String manejoEquipo2;
     private int numGolesEquipo1;
     private int numGolesEquipo2;
     private int numAmarillasEquipo1;
     private int numAmarillasEquipo2;
     private int numRojasEquipo1;
     private int numRojasEquipo2;
     private int cierre;

    public Partidos() {
    }

    public Partidos(String manejoEquipo1, String manejoEquipo2, int numGolesEquipo1, int numGolesEquipo2, int numAmarillasEquipo1, int numAmarillasEquipo2, int numRojasEquipo1, int numRojasEquipo2, int cierre) {
       this.manejoEquipo1 = manejoEquipo1;
       this.manejoEquipo2 = manejoEquipo2;
       this.numGolesEquipo1 = numGolesEquipo1;
       this.numGolesEquipo2 = numGolesEquipo2;
       this.numAmarillasEquipo1 = numAmarillasEquipo1;
       this.numAmarillasEquipo2 = numAmarillasEquipo2;
       this.numRojasEquipo1 = numRojasEquipo1;
       this.numRojasEquipo2 = numRojasEquipo2;
       this.cierre = cierre;
    }
   
    public Integer getCodigoPartido() {
        return this.codigoPartido;
    }
    
    public void setCodigoPartido(Integer codigoPartido) {
        this.codigoPartido = codigoPartido;
    }
    public String getManejoEquipo1() {
        return this.manejoEquipo1;
    }
    
    public void setManejoEquipo1(String manejoEquipo1) {
        this.manejoEquipo1 = manejoEquipo1;
    }
    public String getManejoEquipo2() {
        return this.manejoEquipo2;
    }
    
    public void setManejoEquipo2(String manejoEquipo2) {
        this.manejoEquipo2 = manejoEquipo2;
    }
    public int getNumGolesEquipo1() {
        return this.numGolesEquipo1;
    }
    
    public void setNumGolesEquipo1(int numGolesEquipo1) {
        this.numGolesEquipo1 = numGolesEquipo1;
    }
    public int getNumGolesEquipo2() {
        return this.numGolesEquipo2;
    }
    
    public void setNumGolesEquipo2(int numGolesEquipo2) {
        this.numGolesEquipo2 = numGolesEquipo2;
    }
    public int getNumAmarillasEquipo1() {
        return this.numAmarillasEquipo1;
    }
    
    public void setNumAmarillasEquipo1(int numAmarillasEquipo1) {
        this.numAmarillasEquipo1 = numAmarillasEquipo1;
    }
    public int getNumAmarillasEquipo2() {
        return this.numAmarillasEquipo2;
    }
    
    public void setNumAmarillasEquipo2(int numAmarillasEquipo2) {
        this.numAmarillasEquipo2 = numAmarillasEquipo2;
    }
    public int getNumRojasEquipo1() {
        return this.numRojasEquipo1;
    }
    
    public void setNumRojasEquipo1(int numRojasEquipo1) {
        this.numRojasEquipo1 = numRojasEquipo1;
    }
    public int getNumRojasEquipo2() {
        return this.numRojasEquipo2;
    }
    
    public void setNumRojasEquipo2(int numRojasEquipo2) {
        this.numRojasEquipo2 = numRojasEquipo2;
    }
    public int getCierre() {
        return this.cierre;
    }
    
    public void setCierre(int cierre) {
        this.cierre = cierre;
    }




}


